fixtures:
  repositories:
    stdlib:
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib"
      # for future parser tests with puppet < 4
      ref: "4.25.1"
    alternatives: "git://github.com/puppet-community/puppet-alternatives"
    hadoop: "git://github.com/MetaCenterCloudPuppet/cesnet-hadoop"
    hadoop_lib: "git://github.com/MetaCenterCloudPuppet/cesnet-hadoop_lib"
  symlinks:
    spark: "#{source_dir}"
