---
language: ruby
bundler_args: --without development system_tests
before_install: rm Gemfile.lock || true
rvm:
  - 2.4.1
script: bundle exec rake test
env:
  - PUPPET_GEM_VERSION="~> 5.1.0" STRICT_VARIABLES=yes
  - PUPPET_GEM_VERSION="~> 5.2.0" STRICT_VARIABLES=yes
  - PUPPET_GEM_VERSION="~> 5.3.0" STRICT_VARIABLES=yes
